export { default as CartPage } from './CartPage/CartPage'
export { default as MainPage } from './MainPage/MainPage'
export { default as ProductSinglePage } from './ProductSinglePage/ProductSinglePage'
export { default as ProductsPage } from './ProductsPage/ProductsPage'
export { default as ProfilePage } from './ProfilePage/ProfilePage'
